# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
  - name: "SpacyNLP"
    # language model to load
    model: "vi_spacy_model"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "SpacyEntityExtractor"
  - name: "CRFEntityExtractor"
  - name: "RegexEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"

policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: AugmentedMemoizationPolicy
  - name: TEDPolicy
#    epochs: 40ame
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
