API_VNDIRECT = 'https://finfo-api.vndirect.com.vn/v4/stock_prices/'

PRICE_TYPE_BASIC = 'basicPrice'
PRICE_TYPE_CEILING = 'ceilingPrice'
PRICE_TYPE_FLOOR = 'floorPrice'
PRICE_TYPE_OPEN = 'open'
PRICE_TYPE_HIGH = 'high'
PRICE_TYPE_LOW = 'low'
PRICE_TYPE_CLOSE = 'close'
PRICE_TYPE_AVERAGE = 'average'
PRICE_TYPE_AD_OPEN = 'adOpen'
PRICE_TYPE_VOLUME = 'nmVolume'
PRICE_TYPE_VALUE = 'nmValue'
PRICE_TYPE_AD_CHANGE= 'adChange'
PRICE_TYPE_AD_CHANGE_PCT = 'pctChange'